apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Weather Provider Libraries and API
  description: Provides an interface and library for accessing and transforming a multitude of meteorological datasets 
    into common formats and unit systems using a standardized request format, while maintaining the option to use 
    complex parameters.
  annotations:
    github.com/project-slug: alliander-opensource/Weather-Provider-API
spec:
  owner: weersafhankelijk-netrekenen
  type: lib
  lifecycle: production
  providesApis:
    - wpla
