[tool.poetry]
name = "wpla"
version = "3.0.0-alpha1"
description = "The Weather Provider Libraries and API"
authors = ["Raoul Linnenbank <58594297+rflinnenbank@users.noreply.github.com>"]
license = "MPL2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.18.3"
fastapi = "^0.82.0"
toml = "^0.10.2"
loguru = "^0.6.0"
python-dateutil = "^2.8.2"
starlette-prometheus = "^0.9.0"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.19.0"
pytest = "^7.1.3"
Sphinx = "^5.1.1"
sphinxcontrib-napoleon = "^0.7"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
