[tool.poetry]
name = "weather_provider_api"
version = "2.73.16"
description = "Weather Provider Libraries and API"
authors = ["Verbindingsteam", "Raoul Linnenbank <58594297+rflinnenbank@users.noreply.github.com>"]
license = "MPL-2.0"
readme = "README.md"
repository="https://github.com/alliander-opensource/wpla/"
include = [
    {path = "var_maps/*.json", format = "wheel"}
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "^0.128.0"
requests = "^2.32.5"
geopy = "^2.4.1"
numpy = "^2.4.0"
gunicorn = "^23.0.0"
lxml = "^6.0.2"  # Used by beautifulsoup4
starlette-prometheus = "^0.10.0"
pandas = "^2.3.3"
xarray = "^2025.12.0"
cfgrib = "^0.9.15.0"
uvicorn = "^0.40.0"
slowapi = "^0.1.9"
loguru = "^0.7.3"
eccodes = "^2.40.1"  # Needed for cfgrib
ecmwflibs = "0.6.3"  # Needed for cdsapi
accept-types = "^0.4.1"
cdsapi = "^0.7.7"
beautifulsoup4 = "^4.14.3"
netcdf4 = "^1.7.4"  # Needed for xarray
tomli = "^2.3.0"
pytz = "^2025.2"
starlette = "^0.50.0"
urllib3 = "^2.6.2"
pydantic = "^2.12.5"
email-validator = "^2.3.0"  # Used by pydantic for email validation
python-dateutil = "^2.9.0.post0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
coverage = "^7.13.1"
pytest-cov = "^7.0.0"
pylint = "^4.0.4"
ruff = {version = "^0.4.1", source = "pypi"}
pytest = "^9.0.2"
sphinx = "^8.2.3"
myst-parser = "^4.0.1"
piccolo-theme = "^0.24.0"  # Sphinx theme
fawltydeps = "^0.20.0"

[tool.poetry.scripts]
wpla_update_era5sl = "weather_provider_api.scripts.update_era5sl_repository:main"
wpla_update_era5land = "weather_provider_api.scripts.update_era5land_repository:main"
wpla_update_arome = "weather_provider_api.scripts.update_arome_repository:main"
wpla_update_waarnemingen = "weather_provider_api.scripts.update_waarnemingen_register:main"
wpla_clear_era5sl = "weather_provider_api.scripts.erase_era5sl_repository:main"
wpla_clear_era5land = "weather_provider_api.scripts.erase_era5land_repository:main"
wpla_clear_arome = "weather_provider_api.scripts.erase_arome_repository:main"
wpla_clear_waarnemingen = "weather_provider_api.scripts.erase_waarnemingen_register:main"
wpla_run_api = "weather_provider_api.main:main"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.pylint]
max-line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ANN",  # flake8-annotations
    "E",  # flake8
    "F",  # flake8
    "I",  # isort
    "D",  # pydocstyle
    "S",  # flake8-bandit
    "NPY",  # numpy-specific rules
    "RUF",  # ruff specific rules
]
ignore = [
    "E501",
    "E712",

    "ANN101",  # Missing type annotation for `self` in method
    "ANN202",  # Missing return type annotation for private function
    "ANN204",  # Missing return type annotation for special function
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed

    # pydocstyle
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D106",  # Missing docstring in public nested class
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["S", "ANN"]

[tool.ruff.lint.pydocstyle]
convention = "google"