# SPDX-FileCopyrightText: 2021-2026 Alliander N.V.
#
# SPDX-License-Identifier: MPL-2.0


# Required metadata
sonar.projectKey=alliander-opensource_weather-provider-api
sonar.organization=alliander-opensource
sonar.projectName=Weather Provider Libraries and API
sonar.projectVersion=2.14.0
sonar.sourceEncoding=UTF-8

# Project folders
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**, **/__pycache__/**, **/*.pyc, venv/**, .venv/**, .git/**, dist/**, build/**, var_maps/**, LICENSES/**, docs/**, img/**, .github/**

# Language
sonar.language=py

# Python versions
sonar.python.version=3.12, 3.13

sonar.links.homepage=https://github.com/alliander-opensource/Weather-Provider-API/
sonar.links.ci=https://github.com/alliander-opensource/Weather-Provider-API/img/gitflow.svg
sonar.links.scm=https://github.com/alliander-opensource/Weather-Provider-API/
sonar.links.issue=https://github.com/alliander-opensource/Weather-Provider-API/issues

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
