@startuml
'https://plantuml.com/class-diagram

package base_models.model{
    class WeatherModelBase{

    }
    class WeatherSourceBase{

    }
}

package sources.cds.models{
    class Era5SLModel extends WeatherModelBase{

    }
}

package sources.knmi.models{
    class ActueleWaarnemingenModel implements WeatherModelBase{

    }
    class PluimModel implements WeatherModelBase{

    }
}



@enduml