name: GitHub Pages Deployment
on:
  push:
    branches:
      main*
permissions:
  id-token: write
  pages: write
jobs:
  # ---------------------------------------------------------------- #
  # |  Building and deployment of Sphinx build                     | #
  # ---------------------------------------------------------------- #
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          pip install sphinx piccolo-theme myst_parser
      - name: Sphinx Build
        run: |
          sphinx-build ./sphinx-docs/ _build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build
      - name: Push artifact to pages
        uses: actions/deploy-pages@v3.0.1