name: Release Candidate evaluation
on:
  push:
    branches:
      release-*
jobs:
  # ---------------------------------------------------------------- #
  # |  Coverage and SonarCloud.io upload                           | #
  # ---------------------------------------------------------------- #
  tests-and-sonarcloud:
    strategy:
      matrix:
        version: ["3.13"]  # TODO: Get Python versions from the project
    name: Testing and updating SonarCloud
    runs-on:
      group: managed
    steps:
      # Checkout
      - name: Branch checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      # Install Python
      - name: Setup Python installation
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.version }}
      # Install Poetry
      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update --preview
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      # Install required dependencies
      - name: Install dependencies
        run: poetry install -v --with dev
      # Install ecCodes dependencies
      - name: Install ecCodes
        run: sudo apt-get update && sudo apt-get install -y libeccodes0 libeccodes-dev
      # Run Coverage
      - name: Run Coverage
        env:
          CDSAPI_URL: ${{ secrets.CDSAPI_URL }}
          CDSAPI_KEY: ${{ secrets.CDSAPI_KEY }}
          CDSAPI_VERIFY: 1
          KNMI_DATA_PLATFORM_KEY: ${{ secrets.KNMI_DATA_PLATFORM_KEY }}
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
      # Generate XML Coverage result file
      - if: matrix.version == '3.13'
        name: Generate Coverage XML file
        run: poetry run coverage xml
      # Upload coverage data to SonarCloud.io
      - if: matrix.version == '3.13'
        name: Update SonarCloud.io
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # ---------------------------------------------------------------- #
  # |  Build image and upload it to AWS and DockerHub              | #
  # ---------------------------------------------------------------- #
  create-and-upload-image:
    name: Create and upload image
    needs: tests-and-sonarcloud
    runs-on:
      group: managed
    permissions:
      id-token: write
      contents: read
    environment:
      name: ci
    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          role-to-assume: arn:aws:iam::325973380531:role/dnb-inno-repository-access-role
          aws-region: eu-central-1
      # Install Poetry (needed for version)
      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update --preview
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - name: Determine current version
        run: |
          version="$(poetry version --short)rc${{ github.run_number }}"
          echo "Package version: $version"
          echo "package_version=$version" >> $GITHUB_ENV
      # Create the image and upload it to Amazon ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 325973380531.dkr.ecr.eu-central-1.amazonaws.com
          ECR_REPOSITORY: dnb-inno-image-repository
        run: |
          docker build  --target gunicorn-image -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_RC }}:${{ env.package_version }} .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_RC }}:${{ env.package_version }}
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_RC }} .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_RC }}
